site_name: 2025年度 セキュリティネットワーク科
use_directory_urls: false
theme:
  name: material
  palette:
    primary: green
  alternate:
    - name: Japanese
      link: /
      lang: ja
  features:
    - content.code.copy
plugins:
  search:
    lang: 'ja'
markdown_extensions:
    # コードハイライトの設定
    - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: false
nav:
  - Home: index.md
  - 自己紹介: Introduce_Myself/index.md
  - オリエンテーション: Orientation/index.md
  - Web Application Builder:
    - Web_Application_Builder/index.md
    - フェーズ 1: Web_Application_Builder/phase1/index.md
    - フェーズ 2: Web_Application_Builder/phase2/index.md
    - フェーズ 3: Web_Application_Builder/phase3/index.md
    - フェーズ 4: Web_Application_Builder/phase4/index.md
  - kintone:
    - プラグイン:
      - kintone/plugin/index.md
      - プラグインの管理: kintone/plugin/manage_plugin.md
      - サンプルプラグインの追加: kintone/plugin/sample/add_sample_plugin.md
      - サンプルプラグイン: kintone/plugin/sample/sample_plugin.md
  - 課題一覧: home_works.md
